#docker-compose.yml
version: "3.8"

services:
  server:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

  db:
    image: mariadb:11.5.2
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}